/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'salary' : IDL.Float64,
  'hireDate' : Time,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const LoanApplication = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'applicantName' : IDL.Text,
  'date' : Time,
  'agentName' : IDL.Text,
  'loanType' : IDL.Text,
  'notes' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const AttendanceStatus = IDL.Variant({
  'halfDay' : IDL.Null,
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const Attendance = IDL.Record({
  'status' : AttendanceStatus,
  'date' : IDL.Text,
  'employeeId' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Nat),
  'department' : IDL.Text,
});
export const DSAConnector = IDL.Record({
  'status' : IDL.Text,
  'partnerName' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const DSAPartner = IDL.Record({
  'region' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'phone' : IDL.Text,
  'commissionPercentage' : IDL.Float64,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'note' : IDL.Text,
  'employeeId' : IDL.Nat,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
});
export const JoiningLetter = IDL.Record({
  'dateIssued' : Time,
  'content' : IDL.Text,
  'employeeId' : IDL.Nat,
});
export const OfferLetter = IDL.Record({
  'dateIssued' : Time,
  'content' : IDL.Text,
  'employeeId' : IDL.Nat,
});
export const SalarySlip = IDL.Record({
  'month' : IDL.Text,
  'content' : IDL.Text,
  'salary' : IDL.Float64,
  'year' : IDL.Nat,
  'employeeId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDSAConnector' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addDSAPartner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'addEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'updateEmployee' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'addTransaction' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'applyForLoan' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateJoiningLetter' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'generateOfferLetter' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'generateSalarySlip' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllLoanApplications' : IDL.Func(
      [],
      [IDL.Vec(LoanApplication)],
      ['query'],
    ),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'addLoanDocument' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Nat], []),
  'getLoanDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(LoanDocument)], ['query']),
  'deleteLoanDocument' : IDL.Func([IDL.Nat], [], []),
  'getAttendance' : IDL.Func([IDL.Nat], [IDL.Vec(Attendance)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDSAConnectors' : IDL.Func([], [IDL.Vec(DSAConnector)], ['query']),
  'getDSAPartners' : IDL.Func([], [IDL.Vec(DSAPartner)], ['query']),
  'getDepartments' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getEmployee' : IDL.Func([IDL.Nat], [Employee], ['query']),
  'getEmployeeLocations' : IDL.Func([IDL.Nat], [IDL.Vec(Location)], ['query']),
  'getJoiningLetters' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JoiningLetter)],
      ['query'],
    ),
  'getLoanApplication' : IDL.Func([IDL.Nat], [LoanApplication], ['query']),
  'getOfferLetters' : IDL.Func([IDL.Nat], [IDL.Vec(OfferLetter)], ['query']),
  'getSalarySlips' : IDL.Func([IDL.Nat], [IDL.Vec(SalarySlip)], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAttendance' : IDL.Func([IDL.Nat, IDL.Text, AttendanceStatus], [], []),
  'recordLocation' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'salary' : IDL.Float64,
    'hireDate' : Time,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const LoanDocument = IDL.Record({
    'id' : IDL.Nat,
    'loanId' : IDL.Nat,
    'name' : IDL.Text,
    'fileType' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'blobRef' : IDL.Vec(IDL.Nat8),
  });
  const LoanApplication = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'applicantName' : IDL.Text,
    'date' : Time,
    'agentName' : IDL.Text,
    'loanType' : IDL.Text,
    'notes' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const AttendanceStatus = IDL.Variant({
    'halfDay' : IDL.Null,
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const Attendance = IDL.Record({
    'status' : AttendanceStatus,
    'date' : IDL.Text,
    'employeeId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Nat),
    'department' : IDL.Text,
  });
  const DSAConnector = IDL.Record({
    'status' : IDL.Text,
    'partnerName' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DSAPartner = IDL.Record({
    'region' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'phone' : IDL.Text,
    'commissionPercentage' : IDL.Float64,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'note' : IDL.Text,
    'employeeId' : IDL.Nat,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
  });
  const JoiningLetter = IDL.Record({
    'dateIssued' : Time,
    'content' : IDL.Text,
    'employeeId' : IDL.Nat,
  });
  const OfferLetter = IDL.Record({
    'dateIssued' : Time,
    'content' : IDL.Text,
    'employeeId' : IDL.Nat,
  });
  const SalarySlip = IDL.Record({
    'month' : IDL.Text,
    'content' : IDL.Text,
    'salary' : IDL.Float64,
    'year' : IDL.Nat,
    'employeeId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDSAConnector' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addDSAPartner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'addEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'updateEmployee' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'addTransaction' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'applyForLoan' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateJoiningLetter' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'generateOfferLetter' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'generateSalarySlip' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllLoanApplications' : IDL.Func(
        [],
        [IDL.Vec(LoanApplication)],
        ['query'],
      ),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'addLoanDocument' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Nat], []),
    'getLoanDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(LoanDocument)], ['query']),
    'deleteLoanDocument' : IDL.Func([IDL.Nat], [], []),
  'addLoanDocument' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)], [IDL.Nat], []),
  'getLoanDocuments' : IDL.Func([IDL.Nat], [IDL.Vec(LoanDocument)], ['query']),
  'deleteLoanDocument' : IDL.Func([IDL.Nat], [], []),
    'getAttendance' : IDL.Func([IDL.Nat], [IDL.Vec(Attendance)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDSAConnectors' : IDL.Func([], [IDL.Vec(DSAConnector)], ['query']),
    'getDSAPartners' : IDL.Func([], [IDL.Vec(DSAPartner)], ['query']),
    'getDepartments' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getEmployee' : IDL.Func([IDL.Nat], [Employee], ['query']),
    'getEmployeeLocations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Location)],
        ['query'],
      ),
    'getJoiningLetters' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JoiningLetter)],
        ['query'],
      ),
    'getLoanApplication' : IDL.Func([IDL.Nat], [LoanApplication], ['query']),
    'getOfferLetters' : IDL.Func([IDL.Nat], [IDL.Vec(OfferLetter)], ['query']),
    'getSalarySlips' : IDL.Func([IDL.Nat], [IDL.Vec(SalarySlip)], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [Transaction], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAttendance' : IDL.Func(
        [IDL.Nat, IDL.Text, AttendanceStatus],
        [],
        [],
      ),
    'recordLocation' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };