/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Attendance {
  'status' : AttendanceStatus,
  'date' : string,
  'employeeId' : bigint,
}
export type AttendanceStatus = { 'halfDay' : null } |
  { 'present' : null } |
  { 'absent' : null };
export interface DSAConnector {
  'status' : string,
  'partnerName' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface DSAPartner {
  'region' : string,
  'status' : string,
  'name' : string,
  'contactPerson' : string,
  'phone' : string,
  'commissionPercentage' : number,
}
export interface Employee {
  'id' : bigint,
  'status' : string,
  'salary' : number,
  'hireDate' : Time,
  'name' : string,
  'role' : string,
  'email' : string,
  'department' : string,
}
export interface JoiningLetter {
  'dateIssued' : Time,
  'content' : string,
  'employeeId' : bigint,
}
export interface LoanApplication {
  'id' : bigint,
  'status' : string,
  'applicantName' : string,
  'date' : Time,
  'agentName' : string,
  'loanType' : string,
  'notes' : string,
  'amount' : number,
}
export interface Location {
  'latitude' : number,
  'note' : string,
  'employeeId' : bigint,
  'longitude' : number,
  'timestamp' : Time,
}
export interface OfferLetter {
  'dateIssued' : Time,
  'content' : string,
  'employeeId' : bigint,
}
export interface SalarySlip {
  'month' : string,
  'content' : string,
  'salary' : number,
  'year' : bigint,
  'employeeId' : bigint,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'transactionType' : string,
  'date' : Time,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'employeeId' : [] | [bigint],
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDSAConnector' : ActorMethod<[string, string, string, string], undefined>,
  'addDSAPartner' : ActorMethod<
    [string, string, string, string, number],
    undefined
  >,
  'addEmployee' : ActorMethod<
    [string, string, string, string, number],
    undefined
  >,
  'addTransaction' : ActorMethod<[number, string, string, string], undefined>,
  'applyForLoan' : ActorMethod<
    [string, string, number, string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateJoiningLetter' : ActorMethod<[bigint, string], undefined>,
  'generateOfferLetter' : ActorMethod<[bigint, string], undefined>,
  'generateSalarySlip' : ActorMethod<
    [bigint, string, bigint, string],
    undefined
  >,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllLoanApplications' : ActorMethod<[], Array<LoanApplication>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAttendance' : ActorMethod<[bigint], Array<Attendance>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDSAConnectors' : ActorMethod<[], Array<DSAConnector>>,
  'getDSAPartners' : ActorMethod<[], Array<DSAPartner>>,
  'getDepartments' : ActorMethod<[], Array<string>>,
  'getEmployee' : ActorMethod<[bigint], Employee>,
  'getEmployeeLocations' : ActorMethod<[bigint], Array<Location>>,
  'getJoiningLetters' : ActorMethod<[bigint], Array<JoiningLetter>>,
  'getLoanApplication' : ActorMethod<[bigint], LoanApplication>,
  'getOfferLetters' : ActorMethod<[bigint], Array<OfferLetter>>,
  'getSalarySlips' : ActorMethod<[bigint], Array<SalarySlip>>,
  'getTransaction' : ActorMethod<[bigint], Transaction>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordAttendance' : ActorMethod<
    [bigint, string, AttendanceStatus],
    undefined
  >,
  'recordLocation' : ActorMethod<[bigint, number, number, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];